[workspace]
resolver = "2"
members = [
    "crates/ds3-archipelago",
    "crates/shared",
]

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/fswap/fromsoftware-archipelago"

[workspace.dependencies]
anyhow = "1.0.100"
archipelago_rs = "1.0.0"
bincode = "2.0.1"
fromsoftware-shared = { git = "https://github.com/vswarte/fromsoftware-rs" }
hudhook = "0.8.1"
ilhook = {version = "2.3.0", features = ["x64"]}
json = { package = "serde_json", version = "1.0.145" }
log = "0.4.29"
regex = "1.12.3"
regex-macro = "0.3.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_repr = "0.1.20"
shared = { path = "crates/shared"}

[workspace.dependencies.windows]
version = "0.54"
features = [
    "Win32_Foundation",
    "Win32_System_ProcessStatus",
    "Win32_System_SystemServices",
    "Win32_UI_WindowsAndMessaging",
]

[patch.crates-io]
imgui = { git = "https://github.com/imgui-rs/imgui-rs" }
imgui-sys = { git = "https://github.com/imgui-rs/imgui-rs" }
