[package]
name = "sdt-archipelago"
version = "0.0.0"
edition.workspace = true
repository.workspace = true
license.workspace = true
readme = false

[lib]
crate-type = ["cdylib"]
name = "sdt_archipelago"

[dependencies]
anyhow.workspace = true
archipelago_rs.workspace = true
bincode.workspace = true
sekiro = { git = "https://github.com/fswap/fromsoftware-rs", branch = "sdt-tasks" }
fromsoftware-shared.workspace = true
hudhook.workspace = true
ilhook.workspace = true
json.workspace = true
log.workspace = true
regex-macro.workspace = true
regex.workspace = true
serde.workspace = true
serde_repr.workspace = true
shared.workspace = true
windows.workspace = true
